services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: taskflow-frontend:latest
    ports:
      - 5173:5173
    depends_on:
      - backend
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow-backend:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: on-failure 
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    
    restart: unless-stopped
  
  nginx: 
    image: nginx:latest

    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend
      - backend
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  postgres_data:
